#!/bin/bash

echo "=== 测试日志系统 ==="
echo ""
echo "1. 运行程序 (默认 Debug 级别)"
echo "   日志会输出到终端"
echo ""
echo "2. 使用环境变量设置日志级别:"
echo "   RUST_LOG=trace cargo run   # 最详细"
echo "   RUST_LOG=debug cargo run   # 调试信息"
echo "   RUST_LOG=info cargo run    # 一般信息"
echo "   RUST_LOG=warn cargo run    # 仅警告"
echo "   RUST_LOG=error cargo run   # 仅错误"
echo ""
echo "3. 在程序运行时:"
echo "   - 点击右上角的 '⚙ 日志设置' 按钮"
echo "   - 选择不同的日志等级"
echo "   - 执行操作(如加载文件、选择表)来查看不同级别的日志"
echo ""
echo "按 Ctrl+C 退出程序"
echo ""
